### ISSUE TITLE
Icons in asciidoc are of different sizes on github

### ISSUE THREAD

**Issue by dongsiji** [asciidoctor/asciidoctor.org#817] opened 2018-11-11 07:51 UTC
Why is the icon of different sizes throughout the ascii doc, even though I am using the same size and for this instance it is not even viewable:
![image](https://user-images.githubusercontent.com/35907419/48310393-793c9200-e5c9-11e8-92df-3159f83f3fa7.png)

This is the source code:
![image](https://user-images.githubusercontent.com/35907419/48310402-9e310500-e5c9-11e8-9cba-c30332db59a8.png)

**Comment by mojavelinux** [comment] 2018-11-11 12:32
It looks like the problem may be that it's not resolving the image. Can you check that it's there? Also, could you point me at the repository where this is happening so I get see what HTML is being produced?

**Comment by mojavelinux** [comment] 2018-11-26 23:58
The problem is that the image is not resolving, perhaps because it's not present in the repository. This is not an issue with the asciidoctor.org website. Therefore, I'm closing.

**Closed by mojavelinux** 2018-11-26 23:58 UTC
