### ISSUE TITLE
I deployed the Chinese site. But a file can not load.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor.org#638] opened 2016-12-13 07:31 UTC
I just deployed the Chinese site： <http://asciidoctor.cn>.

But I found that some pages loaded a from from <https://gist.github.com/>. The file is <https://gist.github.com/mojavelinux/5333524.js>. 

We can not access <https://gist.github.com/> in China. 

May you add the file to the repo?

**Comment by mojavelinux** [comment] 2016-12-13 07:40
That just happens to be an example that demonstrates the passthrough block. The problem is that it would defeat the purpose of the example somewhat to load it from another place (since that file is dynamically generated to work with a resource on gist.github.com). We'd need to come up with another example that embeds JavaScript into the page.

**Comment by diguage** [comment] 2016-12-13 08:12
I translate some documents to Chinese. And I deployed the site. I hope more and more Chinese like to write with Asciidoctor.

Click the Chinese flag on the navbar of the header, the site displays the Chinese documents.

The Chinese site link: <http://asciidoctor.cn/zh-cn/>

**Comment by mojavelinux** [comment] 2016-12-13 08:18
That's very nice!

I would actually prefer, however, if the site was the Chinese pages by default. That way, we don't have two versions of the English page floating around. Or do you still need the English pages on the .cn domain to make them accessible in China?

**Comment by diguage** [comment] 2016-12-13 09:37
It does not need the English pages. 
May I create a new repo for the Chinese pages?

**Comment by diguage** [comment] 2016-12-13 12:25
I create a new repo <https://github.com/diguage/asciidoctor.cn>.

**Comment by mojavelinux** [comment] 2016-12-13 20:49
I don't think a separate repo is a good idea because then the documents aren't kept together. I just think we need a new mode in the build / deployment script that prepares the Chinese site at the root. That's very possible.

We also have to keep in mind that we are planning to restructure the whole Asciidoctor site soon(ish), so we have to keep in mind that things are going to change and we want to move together.

**Comment by diguage** [comment] 2016-12-14 02:36
I prefer to the way. 
First, I keep the accessibility of this site  and translate document. 
After the way is ok, I add the documents and redeploy the site.

**Comment by mojavelinux** [comment] 2023-10-24 07:12
Closing issue as the referenced site is no longer maintained.

**Closed by mojavelinux** 2023-10-24 07:12 UTC
