### ISSUE TITLE
Please complete the section on 'custom backends' in 'asciidoctor user manual', on priority

### ISSUE THREAD

**Issue by sums801** [asciidoctor/asciidoctor.org#408] opened 2015-07-19 04:48 UTC
custom backends section of usermanual is not written yet at 
http://asciidoctor.org/docs/user-manual/#custom-backends

If this section is written for initiation of user, then potential coontributors can themselves start helping/contributing to backend efforts like asciidoctor-latex 
Currently without any guidance by the user manual on writing backends , it is uphill difficult for few mortals like us . We may remain end-user, not the contributors to the backend, even if we desire to.
It will be useful for you also, because number of contributors/paches may increase, once the backend is documented. 

A simple (but not trivial) sample custom backend example will also be good to include in the documentation at priority.

**Comment by mojavelinux** [comment] 2015-07-19 07:37
I believe this is a duplicate of #80.

**Comment by mojavelinux** [comment] 2021-10-17 06:55
I'm happy to say that this is now covered by the documentation.

* [Converter Templates](https://docs.asciidoctor.org/asciidoctor/latest/convert/templates/)
* [Custom Converter](https://docs.asciidoctor.org/asciidoctor/latest/convert/custom/)

If you find yourself getting stuck, please be specific about what isn't clear and I'll do my best to improve the documentation.

**Closed by mojavelinux** 2021-10-17 06:55 UTC
