### ISSUE TITLE
"Creating a backend" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#452] opened 2015-12-22 10:44 UTC
http://asciidoctor.org/docs/user-manual/#creating-a-backend is currently available to create content for.

Use Issue #80 as the canonical tracker for this issue, which already has a great content starting point outlined by @mojavelinux 

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment] 2015-12-22 10:49
I'm on the hook for this one.

**Comment by mojavelinux** [comment] 2015-12-22 10:51
Also a duplicate of #408.

**Comment by jaredmorgs** [comment] 2015-12-29 05:18
For the record, #80 is the canonical source of planning for this ticket, and I've updated this issue accordingly. 

Continue all discussion on Issue #80 please. This issue remains open until Issue #80 is resolved, at which point the admonition in the user-manual.adoc can be deleted.

**Comment by mojavelinux** [comment] 2021-10-05 09:55
This issue has been fused into https://github.com/asciidoctor/asciidoctor/issues/3948.

**Closed by mojavelinux** 2021-10-05 09:55 UTC
