### ISSUE TITLE
Subtitle support in the HTML5 backend

### ISSUE THREAD

**Issue by thj-dk** [asciidoctor/asciidoctor.org#423] opened 2015-11-06 13:54 UTC
I would love to see the HTML5 backend support the subtitle notation.
Maybe expand the header to two rows; first one with the title, and second one with the subtitle. And then give the subtitle a smaller font size.

What do you think?

**Comment by mojavelinux** [comment] 2015-12-02 00:27
Actually, the display is not the first thing we need to think about. First, we should get the subtitle into its own HTML element so that it can be styled. The main problem right now is that it isn't being split out.

Could you file this in the core repository instead since it will require a code change to the converter? https://github.com/asciidoctor/asciidoctor

Btw, you can implement subtitle functionality today by making a custom document template. You can use the Document API to split the subtitle just like in the DocBook converter. See https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/document.html.slim

**Comment by PierreR** [comment] 2017-11-08 14:43
:+1: 
I would love this too. I currently don't use subtitle with ": " as it does not work on the HTML5 backend. What I am doing instead is to use the line just below the title for this purpose (which seems to render rather nicely both on pdf and html).

**Comment by programming-wolf** [comment] 2021-03-10 10:58
We ran into that problem in our projects. We produce both PDF and HTML output from the asciidoc files. PDF works perfectly fine. However, the HTML output contains a leading `:`, which shouldn't be there. 
Any news on this, a new HTML converter or maybe even a roadmap? 🙃 
Thanks in advance.

**Comment by mojavelinux** [comment] 2021-03-10 20:45
This issue is now a duplicate of https://github.com/asciidoctor/asciidoctor/issues/2749. Please follow that issue instead.

Keep in mind that you can customize the HTML using templates or by extending the built-in converter, so you don't have to wait for a change to be merged to get this behavior.

**Closed by mojavelinux** 2021-03-10 20:45 UTC
Labels: bug
