### ISSUE TITLE
Support callouts for images

### ISSUE THREAD

**Issue by mogsdad** [asciidoctor/asciidoctor.org#931] opened 2020-03-10 18:52 UTC
To facilitate localization, it would be handy to be able to use callouts to annotate images like process diagrams or screenshots. That way, the images could be universal, and only the callout text would need to be translated.

**Comment by mojavelinux** [comment] 2021-07-22 07:03
This is a duplicate of https://github.com/asciidoctor/asciidoctor/issues/3359.

**Closed by mojavelinux** 2021-07-22 07:03 UTC
